(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("planeCollision",
{ "height":1,
 "layers":[
        {
         "data":[1],
         "height":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":1,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"collision",
         "objects":[
                {
                 "height":0,
                 "id":1,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":5.75,
                         "y":-3.75
                        }, 
                        {
                         "x":15.5,
                         "y":0
                        }, 
                        {
                         "x":20.75,
                         "y":-5
                        }, 
                        {
                         "x":19.75,
                         "y":-14.75
                        }, 
                        {
                         "x":68.25,
                         "y":-14
                        }, 
                        {
                         "x":67.75,
                         "y":-2
                        }, 
                        {
                         "x":78,
                         "y":3.75
                        }, 
                        {
                         "x":83,
                         "y":3.75
                        }, 
                        {
                         "x":82.75,
                         "y":49
                        }, 
                        {
                         "x":67.5,
                         "y":48.75
                        }, 
                        {
                         "x":61,
                         "y":57.75
                        }, 
                        {
                         "x":49.5,
                         "y":57.75
                        }, 
                        {
                         "x":42.25,
                         "y":50.5
                        }, 
                        {
                         "x":29.75,
                         "y":46.75
                        }, 
                        {
                         "x":24,
                         "y":51.5
                        }, 
                        {
                         "x":17.25,
                         "y":49.5
                        }, 
                        {
                         "x":13.75,
                         "y":42.25
                        }, 
                        {
                         "x":16,
                         "y":34
                        }, 
                        {
                         "x":13,
                         "y":24.5
                        }, 
                        {
                         "x":7.25,
                         "y":18.75
                        }, 
                        {
                         "x":1,
                         "y":17.5
                        }, 
                        {
                         "x":-2.75,
                         "y":6.75
                        }, 
                        {
                         "x":-2.25,
                         "y":1.25
                        }, 
                        {
                         "x":-0.25,
                         "y":0
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":3,
                 "y":15
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextobjectid":2,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":73,
 "tilesets":[
        {
         "firstgid":1,
         "source":"tiled.tsx"
        }],
 "tilewidth":88,
 "type":"map",
 "version":"2017.05.26",
 "width":1
});