(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("planeCollision",
{ "height":1,
 "layers":[
        {
         "data":[1],
         "height":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":1,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"Object Layer 1",
         "objects":[
                {
                 "height":0,
                 "id":2,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":22.75,
                         "y":-14.25
                        }, 
                        {
                         "x":68,
                         "y":-13.75
                        }, 
                        {
                         "x":68.5,
                         "y":4.75
                        }, 
                        {
                         "x":81.75,
                         "y":4.5
                        }, 
                        {
                         "x":81.5,
                         "y":48.75
                        }, 
                        {
                         "x":65.5,
                         "y":49.75
                        }, 
                        {
                         "x":59,
                         "y":57.25
                        }, 
                        {
                         "x":49.25,
                         "y":57.25
                        }, 
                        {
                         "x":19,
                         "y":49
                        }, 
                        {
                         "x":8,
                         "y":17.75
                        }, 
                        {
                         "x":-0.25,
                         "y":15.75
                        }, 
                        {
                         "x":-2.25,
                         "y":4.5
                        }, 
                        {
                         "x":-0.5,
                         "y":0.25
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":2.75,
                 "y":15
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextobjectid":3,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":73,
 "tilesets":[
        {
         "firstgid":1,
         "source":"tiled.tsx"
        }],
 "tilewidth":88,
 "type":"map",
 "version":"2017.05.26",
 "width":1
});